import type { MorseSettingsSnapshot, PresetSettingsMutator } from '@morsebrowser/core';
import type { MorseAppContextValue } from '../context/MorseAppContext';

/** Captures the live app state into the shape core's preset/export machinery understands. */
export function buildSnapshotFromApp(app: MorseAppContextValue): MorseSettingsSnapshot {
  return {
    charWPM: app.charWPM,
    effectiveWPM: app.effectiveWPM,
    syncWpm: app.syncWpm,
    koVolume: app.koVolume,
    xtraWordSpaceDits: app.xtraWordSpaceDits,
    stickySets: app.stickySets,
    ifStickySets: app.ifStickySets,
    hideList: app.hideList,
    showRaw: app.showRaw,
    darkMode: app.darkMode,
    autoCloseLessonAccordion: app.autoCloseLessonAccordion,
    ifCustomGroup: app.ifCustomGroup,
    customGroup: app.customGroup,
    voiceEnabled: app.voiceEnabled,
    voiceSpelling: app.voiceSpelling,
    voiceThinkingTime: app.voiceThinkingTime,
    voiceAfterThinkingTime: app.voiceAfterThinkingTime,
    voiceLastOnly: app.voiceLastOnly,
    manualVoice: app.manualVoice,
    speakFirst: app.speakFirst,
    numberOfRepeats: app.numberOfRepeats,
    speakFirstAdditionalWordspaces: app.speakFirstAdditionalWordspaces,
    newlineChunking: app.newlineChunking,
    syncSize: app.syncSize,
    ifOverrideMinMax: app.ifOverrideMinMax,
    overrideMin: app.overrideMin,
    overrideMax: app.overrideMax,
    cardSpace: app.cardSpace,
    speedInterval: app.speedInterval,
    intervalTimingsText: app.intervalTimingsText,
    intervalWpmText: app.intervalWpmText,
    intervalFwpmText: app.intervalFwpmText,
    voiceBufferMaxLength: app.voiceBufferMaxLength,
    voiceVolume: app.voiceVolume,
    isShuffled: app.isShuffled,
    shuffleIntraGroup: app.shuffleIntraGroup,
  };
}

/** Maps core's serialized-setting keys back onto the live app's setters. */
export function buildMutatorFromApp(app: MorseAppContextValue): PresetSettingsMutator {
  return {
    setCharWPM: app.setCharWPM,
    setEffectiveWPM: app.setEffectiveWPM,
    setSyncWpm: app.setSyncWpm,
    setKoVolume: app.setKoVolume,
    setXtraWordSpaceDits: app.setXtraWordSpaceDits,
    setStickySets: app.setStickySets,
    setIfStickySets: app.setIfStickySets,
    setHideList: app.setHideList,
    setShowRaw: app.setShowRaw,
    setDarkMode: app.setDarkMode,
    setAutoCloseLessonAccordion: app.setAutoCloseLessonAccordion,
    setIfCustomGroup: app.setIfCustomGroup,
    setCustomGroup: app.setCustomGroup,
    setVoiceEnabled: app.setVoiceEnabled,
    setVoiceSpelling: app.setVoiceSpelling,
    setVoiceThinkingTime: app.setVoiceThinkingTime,
    setVoiceAfterThinkingTime: app.setVoiceAfterThinkingTime,
    setVoiceLastOnly: app.setVoiceLastOnly,
    setManualVoice: app.setManualVoice,
    setSpeakFirst: app.setSpeakFirst,
    setNumberOfRepeats: app.setNumberOfRepeats,
    setSpeakFirstAdditionalWordspaces: app.setSpeakFirstAdditionalWordspaces,
    setNewlineChunking: app.setNewlineChunking,
    setSyncSize: app.setSyncSize,
    setIfOverrideMinMax: app.setIfOverrideMinMax,
    setOverrideMin: app.setOverrideMin,
    setOverrideMax: app.setOverrideMax,
    setCardSpace: app.setCardSpace,
    setSpeedInterval: app.setSpeedInterval,
    setIntervalTimingsText: app.setIntervalTimingsText,
    setIntervalWpmText: app.setIntervalWpmText,
    setIntervalFwpmText: app.setIntervalFwpmText,
    setVoiceBufferMaxLength: app.setVoiceBufferMaxLength,
    setIsShuffled: app.setIsShuffled,
    setShuffleIntraGroup: app.setShuffleIntraGroup,
  };
}
